name : Agenda PR Pretest

on: [push]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm i

      - run: npm test
